using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Headless;
using Avalonia.Input;
using Avalonia.Threading;
using Avalonia.VisualTree;
using PKHeX.Core;
using PKHeX.Modern;
using PKHeX.Modern.Services;
using PKHeX.Modern.ViewModels;
using PKHeX.Modern.Views;

AppBuilder.Configure<App>().UseSkia().UseHeadless(new AvaloniaHeadlessPlatformOptions { UseHeadlessDrawing = false }).WithInterFont().SetupWithoutStarting();
CoreAdapter.SetLanguage("en");
var dir = args[0];
var library = Path.Combine(dir, "library"); Directory.CreateDirectory(library);
var sav = BlankSaveFile.Get(GameVersion.B);
sav.Language = (int)LanguageID.English; sav.OT = "Teste"; sav.DisplayTID = 123; sav.DisplaySID = 456;
var expectedDate = new DateTime(2012, 5, 14);
sav.SecondsToStart = (uint)(expectedDate - new DateTime(2000, 1, 1)).TotalSeconds;
for (int i = 0; i < 5; i++) File.WriteAllBytes(Path.Combine(library, $"black-{i}.sav"), sav.Write().ToArray());
File.WriteAllText(Path.Combine(library, "readme.txt"), "Arquivo que não é save");
int fails = 0;
void Check(string name, bool ok) { Console.WriteLine($"{(ok ? "OK" : "FAIL")} {name}"); if (!ok) fails++; }
void Pump() { for (int i = 0; i < 4; i++) { Dispatcher.UIThread.RunJobs(); AvaloniaHeadlessPlatform.ForceRenderTimerTick(); } }
void Wait(Task task) { for (int i = 0; i < 1000 && !task.IsCompleted; i++) { Pump(); System.Threading.Thread.Sleep(5); } task.GetAwaiter().GetResult(); Pump(); }
var settings = new AppSettings { SavesFolder = library };
string? opened = null;
var vm = new SaveManagerViewModel(settings, path => opened = path);
var view = new SaveManagerView { DataContext = vm };
var win = new Window { Content = view, Width = 1100, Height = 720 }; win.Show();
Wait(vm.RefreshAsync());
Check("contagem de saves e ignorados", vm.Entries.Count == 5 && vm.Summary.Contains("1 arquivo(s) ignorado(s)"));
var entry = vm.Entries[0];
Check("idioma e início da aventura", entry.LanguageBadge == "EN" && entry.Entry.AdventureStart == expectedDate);
Check("SID visível inicialmente", entry.Details.Contains("SID 456"));
vm.HideSID = true; Pump();
Check("SID oculto e TID preservado", vm.Entries.All(e => !e.Details.Contains("SID") && e.Details.Contains("TID 123")) && settings.HideSaveSID);
Wait(vm.RefreshAsync());
Check("preferência preservada ao atualizar", vm.Entries.All(e => e.HideSID));
var cards = view.GetVisualDescendants().OfType<Border>().Where(c => c.Classes.Contains("saveCard") && c.DataContext is SaveEntryViewModel).ToArray();
cards[0].Focus();
win.KeyPressQwerty(PhysicalKey.ArrowRight, RawInputModifiers.None); Pump();
Check("seta direita seleciona segundo cartão", win.FocusManager!.GetFocusedElement() == cards[1]);
win.KeyPressQwerty(PhysicalKey.ArrowDown, RawInputModifiers.None); Pump();
Check("seta para baixo seleciona próxima linha", win.FocusManager!.GetFocusedElement() == cards[4]);
win.KeyPressQwerty(PhysicalKey.Enter, RawInputModifiers.None); Pump();
Check("Enter abre cartão selecionado", opened == ((SaveEntryViewModel)cards[4].DataContext!).Path);
var search = view.GetVisualDescendants().OfType<TextBox>().First(); search.Focus();
win.KeyPressQwerty(PhysicalKey.ArrowLeft, RawInputModifiers.None); Pump();
Check("setas no campo de busca preservam foco", win.FocusManager!.GetFocusedElement() == search);
win.CaptureRenderedFrame()!.Save(Path.Combine(dir, "savemanager-small.png"));
win.Width = 1500; win.Height = 950; Pump();
win.CaptureRenderedFrame()!.Save(Path.Combine(dir, "savemanager.png"));
vm.Search = "black-3"; Pump();
Check("filtro continua funcionando", vm.Groups.Sum(g => g.Items.Count) == 1);
var invalid = Path.Combine(dir, "invalid"); Directory.CreateDirectory(invalid); File.WriteAllText(Path.Combine(invalid, "invalid.txt"), "x");
var empty = new SaveManagerViewModel(new AppSettings { SavesFolder = invalid }, _ => { }); Wait(empty.RefreshAsync());
Check("ignorados aparecem sem saves", empty.IsEmpty && empty.Summary.Contains("1 arquivo(s) ignorado(s)"));
Check("Gen3 sem data inventada", CoreAdapter.GetAdventureStart(BlankSaveFile.Get(GameVersion.FR)) is null);
var restoredSettings = System.Text.Json.JsonSerializer.Deserialize<AppSettings>(System.Text.Json.JsonSerializer.Serialize(settings))!;
Check("preferência SID serializada", restoredSettings.HideSaveSID);
var shield = (SAV8SWSH)BlankSaveFile.Get(GameVersion.SH);
shield.TrainerCard.StartedYear = 2020; shield.TrainerCard.StartedMonth = 3; shield.TrainerCard.StartedDay = 8;
Check("data do cartão de Sword/Shield", CoreAdapter.GetAdventureStart(shield) == new DateTime(2020, 3, 8));
shield.TrainerCard.StartedMonth = 99;
Check("data inválida não impede leitura", CoreAdapter.GetAdventureStart(shield) is null);
var arceus = (SAV8LA)BlankSaveFile.Get(GameVersion.PLA);
arceus.AdventureStart.Timestamp = new DateTime(2022, 2, 3);
Check("epoch de Legends Arceus", CoreAdapter.GetAdventureStart(arceus) == new DateTime(2022, 2, 3));
var main = new MainViewModel(settings);
main.CurrentPage = main.SaveManager;
Wait(main.SaveManager.RefreshAsync());
var fullWindow = new MainWindow { DataContext = main, Width = 1100, Height = 720 }; fullWindow.Show(); Pump();
fullWindow.CaptureRenderedFrame()!.Save(Path.Combine(dir, "app-small.png"));
fullWindow.Width = 1500; fullWindow.Height = 950; Pump();
fullWindow.CaptureRenderedFrame()!.Save(Path.Combine(dir, "app.png"));
var footer = fullWindow.GetVisualDescendants().OfType<Border>().First(b => b.Classes.Contains("actionBar"));
bool FooterShows(string text) => footer.GetVisualDescendants().OfType<Button>().Any(b => b.IsEffectivelyVisible && b.Content?.ToString() == text);
Check("barra inicial oferece Abrir e Atualizar", FooterShows("Abrir save...") && FooterShows("⟳  Atualizar") && !FooterShows("💾  Salvar"));
main.Open(Path.Combine(library, "black-0.sav")); Pump();
Check("caixas mostram ações e Salvar", FooterShows("⭳  Importar") && FooterShows("💾  Salvar") && !FooterShows("Abrir save..."));
foreach (var page in main.Pages.ToArray())
{
    main.CurrentPage = page; Pump();
    Check("Salvar disponível em " + page.Title, FooterShows("💾  Salvar"));
    if (page != main.Boxes && page != main.Party) Check("sem ações de slot em " + page.Title, !FooterShows("⭳  Importar"));
}
main.CurrentPage = main.Encounters; Pump();
Check("ação contextual de encontro", FooterShows("Usar encontro"));
main.CurrentPage = main.Gifts; Pump();
Check("ação contextual de evento", FooterShows("Usar evento"));
main.CurrentPage = main.SaveManager; Pump();
fullWindow.CaptureRenderedFrame()!.Save(Path.Combine(dir, "actions-saves.png"));
main.IsHelpOpen = true; Pump();
Check("Ajuda oferece Voltar", FooterShows("‹  Voltar") && !FooterShows("💾  Salvar"));
Console.WriteLine(fails == 0 ? "TUDO OK" : $"{fails} FALHAS");
Console.WriteLine("Capturas: " + dir);
return fails == 0 ? 0 : 1;
