using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using Avalonia;
using Avalonia.Headless;
using Avalonia.Threading;
using PKHeX.Core;
using PKHeX.Modern;
using PKHeX.Modern.Services;
using PKHeX.Modern.ViewModels;

AppBuilder.Configure<App>().UseSkia().UseHeadless(new AvaloniaHeadlessPlatformOptions{UseHeadlessDrawing=false}).WithInterFont().SetupWithoutStarting();
var work=args[0];Directory.CreateDirectory(work);int fails=0;
BankStorage.Root=Path.Combine(work,"bank");SaveBackup.Folder=Path.Combine(work,"backups");BankLinks.Reset();
void Check(string n,bool ok){Console.WriteLine($"{(ok?"OK":"FAIL")} {n}");if(!ok)fails++;}
var save=BlankSaveFile.Get(GameVersion.B);save.OT="DEMO";CoreAdapter.Activate(save);
var path=Path.Combine(work,"Black.sav");
PKM Make(ushort species)=>new PK5{Species=species,CurrentLevel=30,OriginalTrainerName="DEMO",Version=GameVersion.B,PID=species,EncryptionConstant=species};
for(int i=0;i<3;i++)save.SetBoxSlotAtIndex(Make((ushort)(i==0?2:i==1?3:1)),0,i,EntityImportSettings.None);
save.SetBoxSlotAtIndex(Make(25),0,5,EntityImportSettings.None);save.SetPartySlotAtIndex(Make(4),0,EntityImportSettings.None);
List<DbEntry> Entries()=>PokemonDatabase.Build([(path,save.Clone())],null,new(),includeBank:false,readOnly:true).Where(e=>e.Pkm.Species<=4).ToList();
Dictionary<DbEntry,(PKM? Pokemon,bool Legal,string? Error)> Converted(IReadOnlyList<DbEntry> entries)=>entries.ToDictionary(e=>e,e=>(Pokemon:(PKM?)e.Pkm.Clone(),Legal:false,Error:(string?)"Illegal synthetic record"));
var entries=Entries();var plan=LivingDexApplication.Prepare(save,path,entries,false,false,false,0,false,Converted(entries));
Check("preview resolves 3-way cycle and occupant",plan.Blocked is null&&plan.Moved==3&&plan.Relocations.Count==1&&plan.Missing>0);
Check("exact relocation",plan.Relocations.Single() is {FromBox:0,FromSlot:5,ToBox:1,ToSlot:0});
Check("party excluded",plan.Placements.All(p=>p.Source!.Box>=0));
var history=new SlotHistory(save);var before=plan.BeforeSlots;var party=save.GetPartySlotAtIndex(0).Data.ToArray();
bool Restored()=>before.All(e=>StoredPokemon.Equal(e.Value,save.GetBoxSlotAtIndex(e.Key.Box,e.Key.Slot)));
PKM? Read(DbEntry e)=>e.Source.IsBank?BankStorage.ReadSlot(BankStorage.GetBoxes(e.Source.Bank!,create:false)[e.Box],e.Slot):save.GetBoxSlotAtIndex(e.Box,e.Slot);
LivingDexApplication.Apply(plan,save,history,Read);
Check("national order applied",Enumerable.Range(0,3).Select(i=>save.GetBoxSlotAtIndex(0,i).Species).SequenceEqual(new ushort[]{1,2,3}));
Check("occupant and party preserved",save.GetBoxSlotAtIndex(1,0).Species==25&&party.SequenceEqual(save.GetPartySlotAtIndex(0).Data));
Check("one undo",history.Count==1);history.Undo();Check("undo restores stored bytes",Restored());history.Redo();Check("redo restores arrangement",save.GetBoxSlotAtIndex(0,0).Species==1);history.Undo();
var failed=false;try{LivingDexApplication.Apply(plan,save,history,Read,n=>{if(n==2)throw new IOException("simulated");});}catch(IOException){failed=true;}
Check("rollback without redo",failed&&Restored()&&!history.CanRedo&&history.Count==0);
var old=save.GetBoxSlotAtIndex(0,0);var altered=old.Clone();altered.CurrentLevel=40;save.SetBoxSlotAtIndex(altered,0,0,EntityImportSettings.None);
Check("changed origin rejected",!LivingDexApplication.Validate(plan,save,Read));save.SetBoxSlotAtIndex(old,0,0,EntityImportSettings.None);
var capacity=LivingDexApplication.Prepare(save,path,entries,false,false,false,save.BoxCount-1,true,Converted(entries));Check("capacity blocked",capacity.Blocked is not null);
var legal=LivingDexApplication.Prepare(save,path,entries,false,false,true,0,false,Converted(entries));Check("illegal candidates excluded with reasons",legal.Placements.Count==0&&legal.Changes.Count==0&&legal.Skipped.Any(s=>s.Contains("Illegal synthetic record")));
BankStorage.CreateBank("Principal");var box=BankStorage.GetBoxes("Principal")[0];var bankPk=Make(7);BankStorage.WriteSlot(box,0,bankPk);
var bankEntry=new DbEntry(new("bank:Principal","Bank",GameVersion.Any,false,"Principal"),bankPk,"Box 1",0,0){EntityFile=BankStorage.GetSlotFile(box,0)};
var bankHash=SHA256.HashData(File.ReadAllBytes(bankEntry.EntityFile!));var withBank=Entries();withBank.Add(bankEntry);var dict=Converted(withBank);dict[bankEntry]=LivingDexApplication.Convert(bankEntry,save);
var copying=LivingDexApplication.Prepare(save,path,withBank,false,false,false,0,false,dict);Check("bank copy preview",copying.Copied==1);
LivingDexApplication.Apply(copying,save,history,Read);Check("Bank stays intact",bankHash.SequenceEqual(SHA256.HashData(File.ReadAllBytes(bankEntry.EntityFile!))));
File.WriteAllBytes(path,save.Write().ToArray());Check("write and reopen checksum",CoreAdapter.LoadSave(path) is {ChecksumsValid:true});
history.Undo();
var foreign=new PK4{Species=7,CurrentLevel=30,Version=GameVersion.Pt,OriginalTrainerName="DEMO"};
var foreignEntry=new DbEntry(new("bank:Principal","Bank",GameVersion.Any,false,"Principal"),foreign,"Box 1",0,0);
Check("preview converts foreign format",LivingDexApplication.Convert(foreignEntry,save).Pokemon is PK5);
var full=save.Clone();
for(int b=1;b<full.BoxCount;b++)for(int s=0;s<full.BoxSlotCount;s++)full.SetBoxSlotAtIndex(Make(25),b,s,EntityImportSettings.None);
var crowded=LivingDexApplication.Prepare(full,path,entries,false,false,false,0,false,Converted(entries));
Check("no relocation space blocks",crowded.Blocked is not null);
var protectedSave=(SAV8SWSH)BlankSaveFile.Get(GameVersion.SH);CoreAdapter.Activate(protectedSave);
var lockPk=new PK8{Species=25,CurrentLevel=20};protectedSave.SetBoxSlotAtIndex(lockPk,0,0,EntityImportSettings.None);
protectedSave.TeamIndexes.TeamSlots[0]=0;protectedSave.TeamIndexes.SetIsTeamLocked(0,true);protectedSave.TeamIndexes.SaveBattleTeams();
var unlockedPk=new PK8{Species=1,CurrentLevel=20};protectedSave.SetBoxSlotAtIndex(unlockedPk,0,2,EntityImportSettings.None);
var protectedPath=Path.Combine(work,"Protected.sav");
var protectedEntries=PokemonDatabase.Build([(protectedPath,protectedSave.Clone())],null,new(),includeBank:false,readOnly:true);
var protectedPlan=LivingDexApplication.Prepare(protectedSave,protectedPath,protectedEntries,false,false,false,0,false,Converted(protectedEntries));
Check("protected slot excluded from arrangement",protectedPlan.Blocked is null&&protectedPlan.Changes.All(k=>k.Box!=0||k.Slot!=0)&&StoredPokemon.Equal(protectedSave.GetBoxSlotAtIndex(0,0),protectedPlan.Arrangement.GetBoxSlotAtIndex(0,0)));
var protectedHistory=new SlotHistory(protectedSave);
LivingDexApplication.Apply(protectedPlan,protectedSave,protectedHistory,e=>protectedSave.GetBoxSlotAtIndex(e.Box,e.Slot));
Check("protected slot remains after apply",StoredPokemon.Equal(lockPk,protectedSave.GetBoxSlotAtIndex(0,0)));
CoreAdapter.Activate(save);
var staleEntries=Entries();staleEntries.Add(bankEntry);var staleConverted=Converted(staleEntries);staleConverted[bankEntry]=LivingDexApplication.Convert(bankEntry,save);
var stalePlan=LivingDexApplication.Prepare(save,path,staleEntries,false,false,false,0,false,staleConverted);
var newer=bankPk.Clone();newer.CurrentLevel=50;BankStorage.WriteSlot(box,0,newer);
Check("Bank origin changed after preview rejected",!LivingDexApplication.Validate(stalePlan,save,Read));BankStorage.WriteSlot(box,0,bankPk);
BankLinks.Attach(bankPk,path,"Black");save.SetBoxSlotAtIndex(bankPk.Clone(),1,1,EntityImportSettings.None);
var linkedEntries=Entries();linkedEntries.Add(new(new(path,"Black",GameVersion.B,true){Save=save.Clone()},save.GetBoxSlotAtIndex(1,1),"Box 2",1,1));linkedEntries.Add(bankEntry);
var linkedConverted=Converted(linkedEntries);linkedConverted[bankEntry]=(bankPk.Clone(),false,null);
var linkedPlan=LivingDexApplication.Prepare(save,path,linkedEntries,false,false,false,0,false,linkedConverted);
Check("existing attached copy wins over Bank",linkedPlan.Placements.Single(p=>p.Pokemon?.Species==7).Copy==false);
save.SetBoxSlotAtIndex(save.BlankPKM,1,1,EntityImportSettings.None);BankLinks.Reset();

var vm=new MainViewModel(new AppSettings{SavesFolder=work,CheckForUpdates=false,LegalMode=false});vm.Open(path);vm.CurrentPage=vm.Pokedex;vm.Pokedex.ShowLivingDex=true;
void Pump(){Dispatcher.UIThread.RunJobs();AvaloniaHeadlessPlatform.ForceRenderTimerTick();}
void Wait(Func<bool> done){var end=DateTime.UtcNow.AddSeconds(60);while(!done()&&DateTime.UtcNow<end){Pump();System.Threading.Thread.Sleep(10);}}
Wait(()=>!vm.Pokedex.LivingDex!.IsBusy);var dex=vm.Pokedex.LivingDex!;dex.ReserveMissing=false;
var task=dex.PreviewApplicationAsync();Wait(()=>task.IsCompleted);Check("real active save preview",dex.ApplicationPreview?.Target==vm.ActiveTab!.Sav&&dex.CanApplyPlan);
var desk=new PKHeX.Modern.Views.MainWindow{DataContext=vm,Width=1440,Height=950};desk.Show();for(int i=0;i<10;i++)Pump();Wait(()=>!dex.IsBusy);task=dex.PreviewApplicationAsync();Wait(()=>task.IsCompleted);desk.CaptureRenderedFrame()?.Save(Path.Combine(work,"livingdex-apply-desktop.png"));desk.Hide();
App.ShowShortcuts=false;var phone=new Avalonia.Controls.Window{Width=892,Height=412,Content=new PKHeX.Modern.Views.MobileShell(vm)};phone.Show();for(int i=0;i<10;i++)Pump();Wait(()=>!dex.IsBusy);task=dex.PreviewApplicationAsync();Wait(()=>task.IsCompleted);for(int i=0;i<10;i++)Pump();phone.CaptureRenderedFrame()?.Save(Path.Combine(work,"livingdex-apply-mobile.png"));
var memoryHash=SHA256.HashData(File.ReadAllBytes(path));
var applyTask=dex.ApplyPreviewAsync();var limit=DateTime.UtcNow.AddSeconds(60);while(!applyTask.IsCompleted&&DateTime.UtcNow<limit){Pump();if(vm.Dialog is {} d)d.Complete(true);System.Threading.Thread.Sleep(10);}
Check("UI Apply confirms and marks dirty",applyTask.IsCompletedSuccessfully&&applyTask.Result&&vm.IsDirty&&vm.ActiveTab!.History.Count==1);
Check("UI Apply keeps disk unchanged",memoryHash.SequenceEqual(SHA256.HashData(File.ReadAllBytes(path))));
vm.UndoCommand.Execute(null);vm.RedoCommand.Execute(null);Check("UI redo available and reapplied",vm.ActiveTab!.History.Count==1);
phone.Close();
Console.WriteLine(fails==0?"TUDO OK":$"{fails} FALHAS");return fails==0?0:1;
